### ISSUE TITLE
Could not find module 'yolo_cpp_dll.dll' (or one of its dependencies). Try using the full path with constructor syntax.

### ISSUE THREAD

**Issue by gavinnn101** [philipperemy/python-darknet-yolo-v4#4]
Sorry for the dumb question but I saw the project defaults look to be setup for linux and I'm trying to use this on windows. I'm getting:

error:
```
PS C:\Users\Gavin\Desktop\darknet_test> & C:/Users/Gavin/AppData/Local/Programs/Python/Python38/python.exe c:/Users/Gavin/Desktop/darknet_test/main.py
C:\darknet\darknet-master\build\darknet\x64\darknet.exe
Traceback (most recent call last):
  File "c:/Users/Gavin/Desktop/darknet_test/main.py", line 13, in <module>
    d = Detector(config_path = cfg, weights_path = weights, meta_path = data, lib_darknet_path = darknet_path, gpu_id=0)
  File "C:\Users\Gavin\AppData\Local\Programs\Python\Python38\lib\site-packages\yolov4\darknet.py", line 43, in __init__
    self.lib, self.has_gpu = init_lib(lib_darknet_path)
  File "C:\Users\Gavin\AppData\Local\Programs\Python\Python38\lib\site-packages\yolov4\helpers.py", line 111, in init_lib
    lib = CDLL(winGPUdll, RTLD_GLOBAL)
  File "C:\Users\Gavin\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\Gavin\AppData\Local\Programs\Python\Python38\lib\site-packages\yolov4\yolo_cpp_dll.dll' (or one of its dependencies). Try using the full path with constructor syntax.
PS C:\Users\Gavin\Desktop\darknet_test> 
```

main.py
```
import numpy as np
from PIL import Image

from yolov4 import Detector

cfg = 'yolov4-retail-wow-tiny.cfg'
weights = 'yolov4-retail-wow-tiny_final.weights'
data = 'retail-wow-tiny.data'
darknet_path = 'C:\\darknet\\darknet-master\\build\\darknet\\x64\\darknet.exe'
print(darknet_path)

# img = Image.open('test.jpg')
d = Detector(config_path = cfg, weights_path = weights, meta_path = data, lib_darknet_path = darknet_path, gpu_id=0)
```

I'm leaning towards this being a problem with not providing a good darknet path but I'm not sure? I saw `  :param lib_darknet_path: Path to the darknet library (.so in linux).` but I'm having a hard time understanding how to translate that to windows.

Appreciate any help with this :)

**Comment by gavinnn101** [comment]
I'll note that I also changed darknet_path `darknet.exe` to `yolo_cpp_dll.dll` but that didn't seem to work either

**Comment by philipperemy** [comment]
@gavinnn101 not sure here I've never tried it on Windows!

**Comment by philipperemy** [comment]
But you can have a look at this repo: https://github.com/AlexeyAB/darknet
It has the original parser (darknet.py) at the root.
And I'm sure it will work on Windows.

**Comment by gavinnn101** [comment]
I played around with it for a while and it seems like it's some sort of path issue. If I `os.chdir("...\darknet\...\x64")` (where `yolo_cpp_dll.dll` was built) at the start of the program it seems to run fine. This is obviously hacky and I feel like there must be an obvious solution but it hasn't clicked for me yet.

**Comment by philipperemy** [comment]
Alright cool that it worked out! It's a bit hacky but it might be the way to go. In Linux/MacOS, libdarknet.so is at the root of the darknet project while it seems that for Windows it's in x64, so that's why it could not find it.

https://github.com/philipperemy/python-darknet-yolo-v4/blob/db68ab2d7e244d5f4b8588c5e99b44ecf163b510/test.py#L31

Can not you update the lib_darknet_path to point to x64/yolo_cpp_dll.dll?

**Comment by gavinnn101** [comment]
Even if I point it to yolo.dll, it seems like init_lib doesn't actually ever use lib_darknet_path unless `if os.name == "nt":` is `False`? Which is never True. I forced it to skip to `lib = CDLL(Path(lib_darknet_path).resolve(), RTLD_GLOBAL)` to use `lib_darknet_path` but it still didn't work unless I `os.chdir("....\x64")`. 

Google seems to imply that when `CDLL(dll_path, RTLD_GLOBAL)` gives me the `module not found` error, it probably can't access the module or some of its other dependencies and I'm guessing it's the latter but I'm having a hard time figuring it out.
